### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Dunxter** [luzea9903/winactivate#36]
![screenshot](https://user-images.githubusercontent.com/24455628/170890585-b881703d-5e58-489c-be98-e84f5000be43.jpg)

A friend of mine's got this error (this operation returned because it timed out). She used winactivate some months ago and it worked fine until a few days ago the infamous "activate windows" title returned.
Multiple tries won't solve the error.

Thanks!

**Comment by Silexium** [comment]
Try the fixes listed [here.](https://github.com/luzea9903/winactivate/issues/33)

**Comment by Dunxter** [comment]
Yesterday the problem fixed itself. No idea why.

Also, we tried the registry solution already earlier, but the START value was already 2. Anyway, I'm closing the issue, thanks for answering!
